import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
const root=path.resolve(import.meta.dirname,'..');
function run(source,env){return spawnSync(process.execPath,['--experimental-strip-types','--input-type=module','--eval',source],{cwd:root,env:{...process.env,...env},encoding:'utf8'});}
test('Sprint 2A Fix Pack B: mutations are atomic and isolated',()=>{const dir=mkdtempSync(path.join(tmpdir(),'pack-b-'));try{const dbPath=path.join(dir,'test.sqlite');const script=String.raw`
import assert from 'node:assert/strict';import {POST} from './app/api/data/route.ts';import {getDatabase,hashPin} from './db/index.ts';const db=getDatabase(),o='http://localhost:3000',d='2026-09-17';
for(const [id,u,role] of [['A','admin','관리자'],['T','att','출석 입력 전용']])db.prepare('INSERT INTO staff_users (id,username,display_name,pin_hash,role,active,created_at,must_change_pin) VALUES (?,?,?,?,?,1,?,0)').run(id,u,u,hashPin(u,'12345678'),role,d);
for(const row of [['P1','원본','운영 종료'],['P2','다른','운영 중']])db.prepare('INSERT INTO programs (id,name,category,delivery_type,session_count,recurrence,location,manager,capacity,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(row[0],row[1],'분류','집단',3,'매주','장소','담당',10,row[2],d);db.exec("INSERT INTO program_runs (id,program_id,round_number,label,start_date,status) VALUES ('R1','P1',1,'1차','2026-10-01','종료'),('RX','P2',1,'X차','2026-10-01','모집 중')");const si=db.prepare('INSERT INTO sessions (id,run_id,session_number,session_date,session_time,location) VALUES (?,?,?,?,?,?)');si.run('S1','R1',1,'2026-10-01','14:00','장소');si.run('S2','R1',2,'2026-10-08','14:00','장소');si.run('S3','R1',3,'2026-10-15','14:00','장소');si.run('SX','RX',1,'2026-10-01','14:00','장소');db.prepare('INSERT INTO assessment_catalog (id,name,min_score,max_score,active,created_at,version,description) VALUES (?,?,?,?,?,?,?,?)').run('X','검사',0,10,1,d,'1','');db.prepare('INSERT INTO program_assessments (program_id,assessment_id,sort_order) VALUES (?,?,?)').run('P1','X',0);
const post=(body,c)=>POST(new Request(o+'/api/data',{method:'POST',headers:{Origin:o,'Content-Type':'application/json',Cookie:c},body:JSON.stringify(body)}));const login=async u=>(await post({action:'login',username:u,pin:'12345678'},'')).headers.get('set-cookie').split(';')[0],admin=await login('admin'),att=await login('att');
let r=await post({action:'updateSessionsBulk',programId:'P1',runId:'R1',sessions:[{id:'S1',sessionDate:'2026-10-02',sessionTime:'15:00',location:'새장소'},{id:'S2',sessionDate:'2026-10-09',sessionTime:'15:00',location:'새장소'}]},admin);assert.equal(r.status,200);assert.equal(db.prepare("SELECT session_date FROM sessions WHERE id='S1'").get().session_date,'2026-10-02');assert.equal(db.prepare("SELECT session_date FROM sessions WHERE id='S3'").get().session_date,'2026-10-15');r=await post({action:'updateSessionsBulk',programId:'P1',runId:'R1',sessions:[{id:'S1',sessionDate:'2026-10-03',sessionTime:'16:00',location:'x'},{id:'S2',sessionDate:'bad',sessionTime:'16:00',location:'x'}]},admin);assert.equal(r.status,400);assert.equal(db.prepare("SELECT session_date FROM sessions WHERE id='S1'").get().session_date,'2026-10-02');r=await post({action:'updateSessionsBulk',programId:'P1',runId:'R1',sessions:[{id:'SX',sessionDate:'2026-10-03',sessionTime:'16:00',location:'x'}]},admin);assert.equal(r.status,400);r=await post({action:'updateSessionsBulk',programId:'P1',runId:'R1',sessions:[{id:'S1',sessionDate:'2026-10-03',sessionTime:'16:00',location:'x'}]},att);assert.equal(r.status,403);
db.exec("CREATE TRIGGER badAudit BEFORE INSERT ON audit_logs WHEN NEW.action='sessions_bulk_update' BEGIN SELECT RAISE(ABORT,'bad'); END");r=await post({action:'updateSessionsBulk',programId:'P1',runId:'R1',sessions:[{id:'S1',sessionDate:'2026-10-03',sessionTime:'16:00',location:'x'}]},admin);assert.equal(r.status,500);assert.equal(db.prepare("SELECT session_date FROM sessions WHERE id='S1'").get().session_date,'2026-10-02');db.exec('DROP TRIGGER badAudit');
r=await post({action:'copyRun',sourceRunId:'R1'},admin);assert.equal(r.status,200);const run=db.prepare("SELECT * FROM program_runs WHERE program_id='P1' AND round_number=2").get();assert.equal(run.status,'모집 중');assert.equal(db.prepare('SELECT COUNT(*) AS count FROM sessions WHERE run_id=?').get(run.id).count,3);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM applications WHERE run_id=?').get(run.id).count,0);db.exec("CREATE TRIGGER badSession BEFORE INSERT ON sessions WHEN NEW.run_id LIKE 'RUN-P1-%' BEGIN SELECT RAISE(ABORT,'bad'); END");const n=db.prepare("SELECT COUNT(*) AS count FROM program_runs WHERE program_id='P1'").get().count;r=await post({action:'copyRun',sourceRunId:'R1'},admin);assert.equal(r.status,500);assert.equal(db.prepare("SELECT COUNT(*) AS count FROM program_runs WHERE program_id='P1'").get().count,n);db.exec('DROP TRIGGER badSession');
r=await post({action:'copyProgram',sourceProgramId:'P1',name:'복사'},admin);assert.equal(r.status,200);const p=db.prepare("SELECT * FROM programs WHERE name='복사'").get();assert.equal(p.status,'운영 중');assert.equal(db.prepare('SELECT COUNT(*) AS count FROM program_assessments WHERE program_id=?').get(p.id).count,1);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM program_runs WHERE program_id=?').get(p.id).count,0);db.exec("CREATE TRIGGER badConfig BEFORE INSERT ON program_assessments WHEN NEW.program_id LIKE 'PRG-%' BEGIN SELECT RAISE(ABORT,'bad'); END");const pc=db.prepare('SELECT COUNT(*) AS count FROM programs').get().count;r=await post({action:'copyProgram',sourceProgramId:'P1',name:'실패'},admin);assert.equal(r.status,500);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM programs').get().count,pc);db.close();console.log('{"ok":true}');
`;const result=run(script,{NODE_ENV:'test',ONMAEUM_TEST_DB_PATH:dbPath,ONMAEUM_BACKUP_DIR:path.join(dir,'backups'),ONMAEUM_BOOTSTRAP_ADMIN_USERNAME:'owner',ONMAEUM_BOOTSTRAP_ADMIN_DISPLAY_NAME:'owner',ONMAEUM_BOOTSTRAP_ADMIN_PIN:'87654321',ONMAEUM_ENABLE_DEMO_SEED:'0'});assert.equal(result.status,0,result.stderr||result.stdout)}finally{rmSync(dir,{recursive:true,force:true})}});