'use client';

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';

type Participant = { id:string; name:string; birth_date:string; phone:string; note:string; created_at:string; program_count:number; last_visit:string|null };
type Program = { id:string; name:string; category:string; date:string; time:string; location:string; manager:string; capacity:number; status:string; registered_count:number };
type Registration = { id:number; participant_id:string; program_id:string; applied_at:string; attendance:string; participant_name:string; birth_date:string; program_name:string; date:string; time:string; location:string };
type Certificate = { id:number; participant_id:string; participant_name:string; issued_at:string; program_count:number };
type Data = { participants:Participant[]; programs:Program[]; registrations:Registration[]; certificates:Certificate[] };
type View = 'dashboard'|'participants'|'programs'|'attendance'|'certificates';

const emptyData:Data = { participants:[], programs:[], registrations:[], certificates:[] };
const labels:Record<View,string> = { dashboard:'대시보드', participants:'참가자 관리', programs:'프로그램 관리', attendance:'출석 관리', certificates:'확인서 발급' };
const icons:Record<View,string> = { dashboard:'⌂', participants:'♙', programs:'▣', attendance:'✓', certificates:'▤' };
const formatDate = (value:string|null) => value ? value.replace(/-/g,'. ') : '-';
const maskPhone = (value:string) => value.replace(/(\d{3})-(\d{2})\d{2}-(\d{2})\d{2}/,'$1-$2**-$2**');

export default function Home() {
  const [data,setData] = useState<Data>(emptyData); const [loading,setLoading]=useState(true); const [view,setView]=useState<View>('dashboard');
  const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Participant|null>(null); const [modal,setModal]=useState<'participant'|'program'|'register'|null>(null); const [toast,setToast]=useState('');
  const fileRef=useRef<HTMLInputElement>(null);
  const refresh=async()=>{ setLoading(true); try{const res=await fetch('/api/data');const json=await res.json();if(!res.ok)throw new Error(json.error);setData(json)}catch(e){setToast(e instanceof Error?e.message:'데이터 오류')}finally{setLoading(false)} };
  useEffect(()=>{refresh()},[]);
  const post=async(body:Record<string,unknown>)=>{const res=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const json=await res.json();if(!res.ok)throw new Error(json.error);setData(json);return json};
  const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),2800)};
  const searchResults=useMemo(()=>data.participants.filter(p=>`${p.name} ${p.id} ${p.birth_date}`.toLowerCase().includes(query.toLowerCase())),[data.participants,query]);
  const history=selected?data.registrations.filter(r=>r.participant_id===selected.id):[];

  const importExcel=async(file:File)=>{try{const XLSX=await import('xlsx');const workbook=XLSX.read(await file.arrayBuffer());const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(workbook.Sheets[workbook.SheetNames[0]]);const rows=raw.map(r=>({name:r['이름']??r['성명'],birthDate:r['생년월일']??'',phone:r['연락처']??r['전화번호']??'',programName:r['프로그램']??r['프로그램명']??'',appliedAt:r['신청일']??'',attendance:r['출석상태']??'신청'}));await post({action:'import',rows});notify(`${rows.length}행을 확인해 가져왔습니다.`)}catch(e){notify(e instanceof Error?e.message:'파일을 읽지 못했습니다.')}};
  const exportExcel=async()=>{const XLSX=await import('xlsx');const rows=data.registrations.map(r=>({관리번호:r.participant_id,이름:r.participant_name,생년월일:r.birth_date,프로그램명:r.program_name,프로그램일:r.date,신청일:r.applied_at,출석상태:r.attendance}));const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'프로그램 신청명단');XLSX.writeFile(wb,`프로그램_신청명단_${new Date().toISOString().slice(0,10)}.xlsx`)};
  const makeTemplate=async()=>{const XLSX=await import('xlsx');const ws=XLSX.utils.json_to_sheet([{이름:'홍길동',생년월일:'1990-01-01',연락처:'010-0000-0000',프로그램명:'마음챙김 명상교실',신청일:'2025-08-20',출석상태:'신청'}]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'신청명단');XLSX.writeFile(wb,'프로그램_신청명단_양식.xlsx')};
  const openCertificate=(person:Participant)=>{setSelected(person);setView('certificates')};

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">온</span><span>온마음센터</span></div><nav aria-label="주 메뉴">{(Object.keys(labels) as View[]).map(key=><button key={key} onClick={()=>setView(key)} className={`nav-item ${view===key?'active':''}`}><span>{icons[key]}</span>{labels[key]}</button>)}</nav><div className="sidebar-foot"><button className="nav-item"><span>⚙</span>설정</button><div className="manager"><span className="avatar">관</span><span><b>관리자</b><small>프로그램 담당자</small></span><span>⋮</span></div></div></aside>
    <section className="workspace"><header className="topbar"><button className="mobile-menu" aria-label="메뉴">☰</button><div className="top-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>setView('participants')} placeholder="참가자, 프로그램을 검색하세요" /></div><button className="icon-button" aria-label="알림">♢<i/></button><button className="today">2025년 8월 25일</button></header>
      <div className="content">{loading&&<div className="loading-bar"/>}
        {view==='dashboard'&&<Dashboard data={data} query={query} setQuery={setQuery} results={searchResults} onSelect={setSelected} onNew={()=>setModal('participant')} onView={setView}/>} 
        {view==='participants'&&<Participants data={data} query={query} setQuery={setQuery} onSelect={setSelected} onNew={()=>setModal('participant')} onImport={()=>fileRef.current?.click()} onExport={exportExcel} onTemplate={makeTemplate}/>} 
        {view==='programs'&&<Programs data={data} onNew={()=>setModal('program')} onRegister={()=>setModal('register')}/>} 
        {view==='attendance'&&<Attendance data={data} onAttendance={async(id,status)=>{await post({action:'attendance',id,attendance:status});notify('출석 상태를 저장했습니다.')}}/>}
        {view==='certificates'&&<Certificates data={data} selected={selected} setSelected={setSelected} onIssue={async(person,count)=>{await post({action:'certificate',participantId:person.id,programCount:count});notify('발급 이력을 저장했습니다.');setTimeout(()=>window.print(),100)}}/>}
      </div>
    </section>
    <input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)importExcel(f);e.currentTarget.value=''}}/>
    {selected&&view!=='certificates'&&<HistoryModal person={selected} history={history} onClose={()=>setSelected(null)} onCertificate={()=>openCertificate(selected)}/>} 
    {modal==='participant'&&<ParticipantModal onClose={()=>setModal(null)} onSubmit={async form=>{await post({action:'createParticipant',...form});setModal(null);notify('참가자를 등록했습니다.')}}/>}
    {modal==='program'&&<ProgramModal onClose={()=>setModal(null)} onSubmit={async form=>{await post({action:'createProgram',...form});setModal(null);notify('프로그램을 등록했습니다.')}}/>}
    {modal==='register'&&<RegisterModal data={data} onClose={()=>setModal(null)} onSubmit={async(participantId,programId)=>{await post({action:'register',participantId,programId});setModal(null);notify('신청 명단에 추가했습니다.')}}/>}
    {toast&&<div className="toast" role="status">✓ {toast}</div>}
  </main>;
}

function PageHeading({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="page-heading"><div><p className="eyebrow">PROGRAM CARE</p><h1>{title}</h1><p>{description}</p></div>{action}</div>}

function Dashboard({data,query,setQuery,results,onSelect,onNew,onView}:{data:Data;query:string;setQuery:(s:string)=>void;results:Participant[];onSelect:(p:Participant)=>void;onNew:()=>void;onView:(v:View)=>void}){
 const todayPrograms=data.programs.slice(0,3);return <><PageHeading title="좋은 아침이에요, 관리자님" description="오늘 예정된 프로그램과 참가자 현황을 확인하세요." action={<button onClick={onNew} className="primary-button">＋ 새 참가자 등록</button>}/>
 <section className="stats-grid"><Stat tone="coral" icon="♙" label="전체 참가자" value={data.participants.length} unit="명" note="참가자 통합 명부"/><Stat tone="teal" icon="▣" label="운영 프로그램" value={data.programs.length} unit="개" note="신청 명단 통합"/><Stat tone="blue" icon="✓" label="전체 참여 기록" value={data.registrations.length} unit="건" note={`참석 ${data.registrations.filter(r=>r.attendance==='참석').length}건`}/><Stat tone="sand" icon="▤" label="확인서 발급" value={data.certificates.length} unit="건" note="발급 이력 보관"/></section>
 <section className="quick-search"><div className="search-copy"><span className="search-orb">⌕</span><div><h2>참가자 빠른 검색</h2><p>이름, 생년월일 또는 관리번호로 참여 이력을 바로 확인하세요.</p></div></div><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: 김민준 또는 P-2025-0142"/><kbd>Enter</kbd></div>{query&&<div className="search-results">{results.length?results.slice(0,4).map(p=><button key={p.id} onClick={()=>onSelect(p)}><b>{p.name}</b><span>{p.id} · {formatDate(p.birth_date)} · 참여 {p.program_count}회</span><em>이력 보기 →</em></button>):<p>일치하는 참가자가 없습니다.</p>}</div>}</section>
 <div className="dashboard-grid"><section className="panel schedule-panel"><div className="panel-head"><div><h2>프로그램 일정</h2><p>예정 및 진행 프로그램</p></div><button onClick={()=>onView('programs')}>전체 일정 보기 →</button></div><div className="schedule-list">{todayPrograms.map((p,i)=><article key={p.id}><time><b>{p.time}</b><span>{p.time<'12:00'?'오전':'오후'}</span></time><div className="time-line"><i className={`dot ${['coral-bg','teal-bg','blue-bg'][i]}`}/></div><div className="program-info"><h3>{p.name}</h3><p>{p.location} · 담당 {p.manager}</p></div><div className="people"><b>{p.registered_count} / {p.capacity}명</b></div><span className={`status ${p.status==='진행 중'?'ongoing':'upcoming'}`}>{p.status}</span></article>)}</div></section><section className="panel recent-panel"><div className="panel-head"><div><h2>최근 등록 참가자</h2><p>최근 등록순</p></div><button onClick={()=>onView('participants')}>전체 보기 →</button></div><div className="participant-list">{data.participants.slice(0,4).map((p,i)=><button key={p.id} onClick={()=>onSelect(p)}><span className={`person-avatar tone-${i}`}>{p.name.slice(-1)}</span><span><b>{p.name}</b><small>{p.id}</small></span><span className="program-count">{p.program_count}개 참여</span><em>›</em></button>)}</div></section></div><Privacy/></>}
function Stat({tone,icon,label,value,unit,note}:{tone:string;icon:string;label:string;value:number;unit:string;note:string}){return <article className={`stat-card ${tone}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}<small>{unit}</small></strong><em>{note}</em></div></article>}

function Participants({data,query,setQuery,onSelect,onNew,onImport,onExport,onTemplate}:{data:Data;query:string;setQuery:(s:string)=>void;onSelect:(p:Participant)=>void;onNew:()=>void;onImport:()=>void;onExport:()=>void;onTemplate:()=>void}){const rows=data.participants.filter(p=>`${p.name}${p.id}${p.birth_date}`.includes(query));return <><PageHeading title="참가자 관리" description="참가자를 검색하고 프로그램 참여 이력을 확인합니다." action={<button onClick={onNew} className="primary-button">＋ 참가자 등록</button>}/><div className="toolbar"><div className="table-search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름, 생년월일, 관리번호 검색"/></div><button onClick={onTemplate}>양식 받기</button><button onClick={onImport}>↑ Excel 가져오기</button><button onClick={onExport}>↓ Excel 내보내기</button></div><div className="data-panel"><table><thead><tr><th>관리번호</th><th>이름</th><th>생년월일</th><th>연락처</th><th>참여 프로그램</th><th>최근 참여일</th><th/></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><code>{p.id}</code></td><td><b>{p.name}</b></td><td>{formatDate(p.birth_date)}</td><td>{maskPhone(p.phone)}</td><td><span className="count-pill">{p.program_count}회</span></td><td>{formatDate(p.last_visit)}</td><td><button className="text-button" onClick={()=>onSelect(p)}>이력 보기 →</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="검색 결과가 없습니다."/>}</div><div className="import-guide"><b>Excel 신청 명단 연동</b><span>‘양식 받기’ 파일의 열 이름을 유지해 입력하면 참가자와 프로그램 신청 내역을 한 번에 가져옵니다. 같은 이름과 생년월일은 중복 등록하지 않습니다.</span></div></>}

function Programs({data,onNew,onRegister}:{data:Data;onNew:()=>void;onRegister:()=>void}){return <><PageHeading title="프로그램 관리" description="프로그램 일정과 신청 인원을 한눈에 관리합니다." action={<div className="heading-actions"><button onClick={onRegister} className="secondary-button">＋ 신청자 추가</button><button onClick={onNew} className="primary-button">＋ 프로그램 등록</button></div>}/><div className="program-grid">{data.programs.map((p,i)=><article className="program-card" key={p.id}><div className={`program-color color-${i%4}`}/><div className="program-card-body"><div className="card-top"><span>{p.category}</span><i className={`status ${p.status==='완료'?'done':p.status==='진행 중'?'ongoing':'upcoming'}`}>{p.status}</i></div><h2>{p.name}</h2><p>▦ {formatDate(p.date)} · {p.time}</p><p>⌖ {p.location} · 담당 {p.manager}</p><div className="capacity"><span><b>{p.registered_count}</b> / {p.capacity}명 신청</span><div><i style={{width:`${Math.min(100,p.registered_count/p.capacity*100)}%`}}/></div></div></div></article>)}</div></>}

function Attendance({data,onAttendance}:{data:Data;onAttendance:(id:number,status:string)=>void}){const [programId,setProgramId]=useState(data.programs[0]?.id??'');useEffect(()=>{if(!programId&&data.programs[0])setProgramId(data.programs[0].id)},[data.programs,programId]);const rows=data.registrations.filter(r=>r.program_id===programId);const program=data.programs.find(p=>p.id===programId);return <><PageHeading title="출석 관리" description="프로그램별 참석 여부를 빠르게 기록합니다."/><div className="attendance-head"><label>프로그램 선택<select value={programId} onChange={e=>setProgramId(e.target.value)}>{data.programs.map(p=><option key={p.id} value={p.id}>{formatDate(p.date)} · {p.name}</option>)}</select></label>{program&&<div><b>{program.name}</b><span>{formatDate(program.date)} {program.time} · {program.location}</span></div>}</div><div className="data-panel"><table><thead><tr><th>번호</th><th>참가자</th><th>생년월일</th><th>신청일</th><th>출석 상태</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td><b>{r.participant_name}</b><small className="sub-id">{r.participant_id}</small></td><td>{formatDate(r.birth_date)}</td><td>{formatDate(r.applied_at)}</td><td><div className="attendance-buttons">{['참석','결석','신청'].map(s=><button onClick={()=>onAttendance(r.id,s)} className={r.attendance===s?`selected ${s}`:''} key={s}>{s==='참석'?'✓ ':s==='결석'?'× ':''}{s}</button>)}</div></td></tr>)}</tbody></table>{!rows.length&&<Empty text="이 프로그램에 등록된 신청자가 없습니다."/>}</div></>}

function Certificates({data,selected,setSelected,onIssue}:{data:Data;selected:Participant|null;setSelected:(p:Participant|null)=>void;onIssue:(p:Participant,count:number)=>void}){const [q,setQ]=useState('');const people=data.participants.filter(p=>`${p.name}${p.id}`.includes(q));const attended=selected?data.registrations.filter(r=>r.participant_id===selected.id&&r.attendance==='참석'):[];return <><div className="no-print"><PageHeading title="참여확인서 발급" description="참가자를 선택하면 확인된 참석 기록만 확인서에 반영됩니다."/><div className="certificate-layout"><section className="panel certificate-search"><div className="table-search">⌕ <input value={q} onChange={e=>setQ(e.target.value)} placeholder="참가자 검색"/></div>{people.slice(0,8).map(p=><button className={selected?.id===p.id?'active':''} onClick={()=>setSelected(p)} key={p.id}><span className="person-avatar tone-1">{p.name.slice(-1)}</span><span><b>{p.name}</b><small>{p.id} · 참여 {p.program_count}회</small></span></button>)}</section><section className="certificate-wrap">{selected?<CertificatePaper person={selected} history={attended}/>:<Empty text="왼쪽에서 확인서를 발급할 참가자를 선택하세요."/>}</section></div>{selected&&<div className="certificate-actions"><button className="secondary-button" onClick={()=>setSelected(null)}>선택 해제</button><button className="primary-button" disabled={!attended.length} onClick={()=>onIssue(selected,attended.length)}>▤ 발급 이력 저장 후 인쇄</button></div>}<section className="issue-log"><h2>최근 발급 이력</h2>{data.certificates.slice(0,5).map(c=><span key={c.id}><b>{c.participant_name}</b><em>{c.program_count}개 프로그램</em><small>{formatDate(c.issued_at)}</small></span>)}</section></div>{selected&&<div className="print-only"><CertificatePaper person={selected} history={attended}/></div>}</>}
function CertificatePaper({person,history}:{person:Participant;history:Registration[]}){return <article className="certificate-paper"><div className="cert-mark">온</div><p className="cert-no">발급번호 ON-{new Date().getFullYear()}-{person.id.slice(-4)}</p><h1>프로그램 참여확인서</h1><div className="cert-person"><span>성명 <b>{person.name}</b></span><span>생년월일 <b>{formatDate(person.birth_date)}</b></span></div><table><thead><tr><th>참여일</th><th>프로그램명</th><th>장소</th></tr></thead><tbody>{history.map(r=><tr key={r.id}><td>{formatDate(r.date)}</td><td>{r.program_name}</td><td>{r.location}</td></tr>)}</tbody></table><p className="cert-statement">위 사람은 상기 프로그램에 성실히 참여하였음을 확인합니다.</p><p className="cert-date">{new Date().getFullYear()}년 {new Date().getMonth()+1}월 {new Date().getDate()}일</p><div className="cert-sign"><b>온마음센터장</b><i>직인</i></div></article>}

function HistoryModal({person,history,onClose,onCertificate}:{person:Participant;history:Registration[];onClose:()=>void;onCertificate:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal history-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><div className="profile-head"><span className="person-avatar tone-0">{person.name.slice(-1)}</span><div><h2>{person.name}</h2><p>{person.id} · {formatDate(person.birth_date)} · {maskPhone(person.phone)}</p></div></div><h3>프로그램 참여 이력 <span>{history.length}건</span></h3><div className="history-list">{history.map(r=><article key={r.id}><time>{formatDate(r.date)}<small>{r.time}</small></time><div><b>{r.program_name}</b><span>{r.location}</span></div><i className={`attendance-tag ${r.attendance}`}>{r.attendance}</i></article>)}{!history.length&&<Empty text="아직 등록된 참여 이력이 없습니다."/>}</div><div className="modal-actions"><button className="secondary-button" onClick={onClose}>닫기</button><button className="primary-button" onClick={onCertificate}>▤ 참여확인서 보기</button></div></section></div>}
function BaseModal({title,children,onClose,onSubmit}:{title:string;children:React.ReactNode;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal form-modal" onSubmit={onSubmit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary-button">저장하기</button></div></form></div>}
function ParticipantModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:(f:Record<string,string>)=>void}){return <BaseModal title="새 참가자 등록" onClose={onClose} onSubmit={e=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>)}}><div className="form-grid"><label>이름<input name="name" required placeholder="성명"/></label><label>생년월일<input name="birthDate" type="date" required/></label><label className="full">연락처<input name="phone" required placeholder="010-0000-0000"/></label><label className="full">메모<textarea name="note" placeholder="업무에 필요한 최소 정보만 입력하세요."/></label></div></BaseModal>}
function ProgramModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:(f:Record<string,string>)=>void}){return <BaseModal title="새 프로그램 등록" onClose={onClose} onSubmit={e=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>)}}><div className="form-grid"><label className="full">프로그램명<input name="name" required/></label><label>분류<input name="category" required placeholder="예: 정서회복"/></label><label>정원<input name="capacity" required type="number" min="1" defaultValue="10"/></label><label>날짜<input name="date" required type="date"/></label><label>시간<input name="time" required type="time"/></label><label>장소<input name="location" required/></label><label>담당자<input name="manager" required/></label></div></BaseModal>}
function RegisterModal({data,onClose,onSubmit}:{data:Data;onClose:()=>void;onSubmit:(p:string,g:string)=>void}){return <BaseModal title="프로그램 신청자 추가" onClose={onClose} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit(String(f.get('participantId')),String(f.get('programId')))}}><div className="form-grid"><label className="full">참가자<select name="participantId" required>{data.participants.map(p=><option key={p.id} value={p.id}>{p.name} · {p.id}</option>)}</select></label><label className="full">신청 프로그램<select name="programId" required>{data.programs.map(p=><option key={p.id} value={p.id}>{formatDate(p.date)} · {p.name}</option>)}</select></label></div></BaseModal>}
function Empty({text}:{text:string}){return <div className="empty"><span>⌕</span><p>{text}</p></div>};function Privacy(){return <section className="notice"><span>i</span><div><b>개인정보 보호 안내</b><p>참가자 정보는 업무 목적으로만 열람하고, 사용 후 반드시 로그아웃해 주세요.</p></div><button>확인</button></section>}
