// Declarative reference for the current runtime schema. Production migrations are
// owned by schema-management.ts; historical files under drizzle/ are not executed.
import { index, integer, primaryKey, real, sqliteTable, text, unique } from 'drizzle-orm/sqlite-core';

export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const participants=sqliteTable('participants',{id:text('id').primaryKey(),name:text('name').notNull(),gender:text('gender').notNull().default('미입력'),age:integer('age').notNull().default(0),phone:text('phone').notNull().default(''),memberStatus:text('member_status').notNull().default('비회원'),note:text('note').notNull().default(''),createdAt:text('created_at').notNull()},table=>[index('idx_participants_name').on(table.name)]);
export const programs=sqliteTable('programs',{id:text('id').primaryKey(),name:text('name').notNull(),category:text('category').notNull(),deliveryType:text('delivery_type').notNull().default('집단'),sessionCount:integer('session_count').notNull().default(1),recurrence:text('recurrence').notNull().default('매주'),location:text('location').notNull().default(''),manager:text('manager').notNull().default(''),capacity:integer('capacity').notNull().default(10),status:text('status').notNull().default('운영 중'),createdAt:text('created_at').notNull()});
export const programRuns=sqliteTable('program_runs',{id:text('id').primaryKey(),programId:text('program_id').notNull().references(()=>programs.id,{onDelete:'cascade'}),roundNumber:integer('round_number').notNull(),label:text('label').notNull(),startDate:text('start_date').notNull(),status:text('status').notNull().default('모집 중'),closedAt:text('closed_at'),closedBy:text('closed_by')},table=>[unique().on(table.programId,table.roundNumber),index('idx_runs_program').on(table.programId,table.roundNumber)]);
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),runId:text('run_id').notNull().references(()=>programRuns.id,{onDelete:'cascade'}),sessionNumber:integer('session_number').notNull(),sessionDate:text('session_date').notNull(),sessionTime:text('session_time').notNull(),location:text('location').notNull(),attendanceStatus:text('attendance_status').notNull().default('작성 중'),attendanceClosedAt:text('attendance_closed_at'),attendanceClosedBy:text('attendance_closed_by'),reopenReason:text('reopen_reason').notNull().default('')},table=>[unique().on(table.runId,table.sessionNumber),index('idx_sessions_run_date').on(table.runId,table.sessionDate),index('idx_sessions_attendance_status').on(table.attendanceStatus,table.sessionDate)]);
export const applications=sqliteTable('applications',{id:integer('id').primaryKey({autoIncrement:true}),participantId:text('participant_id').notNull().references(()=>participants.id,{onDelete:'cascade'}),programId:text('program_id').notNull().references(()=>programs.id,{onDelete:'cascade'}),runId:text('run_id').references(()=>programRuns.id,{onDelete:'set null'}),appliedAt:text('applied_at').notNull(),status:text('status').notNull().default('신청'),queueNumber:integer('queue_number'),statusReason:text('status_reason').notNull().default(''),statusUpdatedAt:text('status_updated_at').notNull().default(''),assignedAt:text('assigned_at')},table=>[unique().on(table.participantId,table.programId),index('idx_applications_participant').on(table.participantId),index('idx_applications_program').on(table.programId),index('idx_applications_run').on(table.runId),index('idx_applications_program_run').on(table.programId,table.runId),index('idx_applications_workflow').on(table.status,table.runId,table.appliedAt)]);
export const attendance=sqliteTable('attendance',{id:integer('id').primaryKey({autoIncrement:true}),applicationId:integer('application_id').notNull().references(()=>applications.id,{onDelete:'cascade'}),sessionId:text('session_id').notNull().references(()=>sessions.id,{onDelete:'cascade'}),status:text('status').notNull().default('미입력'),note:text('note').notNull().default(''),contactedAt:text('contacted_at'),makeupForSessionId:text('makeup_for_session_id').references(()=>sessions.id,{onDelete:'set null'})},table=>[unique().on(table.applicationId,table.sessionId),index('idx_attendance_application').on(table.applicationId),index('idx_attendance_session').on(table.sessionId),index('idx_attendance_makeup_session').on(table.makeupForSessionId)]);
export const certificates=sqliteTable('certificates',{id:integer('id').primaryKey({autoIncrement:true}),participantId:text('participant_id').notNull().references(()=>participants.id),issuedAt:text('issued_at').notNull(),sessionCount:integer('session_count').notNull()},table=>[index('idx_certificates_participant').on(table.participantId)]);
export const auditLogs=sqliteTable('audit_logs',{id:integer('id').primaryKey({autoIncrement:true}),createdAt:text('created_at').notNull(),actor:text('actor').notNull(),action:text('action').notNull(),entityType:text('entity_type').notNull(),entityId:text('entity_id').notNull(),beforeJson:text('before_json').notNull().default(''),afterJson:text('after_json').notNull().default(''),summary:text('summary').notNull().default(''),ipAddress:text('ip_address').notNull().default(''),reason:text('reason').notNull().default('')},table=>[index('idx_audit_created').on(table.createdAt),index('idx_audit_entity').on(table.entityType,table.entityId)]);
export const staffUsers=sqliteTable('staff_users',{id:text('id').primaryKey(),username:text('username').notNull().unique(),displayName:text('display_name').notNull(),pinHash:text('pin_hash').notNull(),role:text('role').notNull().default('일반 담당자'),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull(),failedAttempts:integer('failed_attempts').notNull().default(0),lockedUntil:text('locked_until'),lastLoginAt:text('last_login_at'),pinChangedAt:text('pin_changed_at'),mustChangePin:integer('must_change_pin').notNull().default(0)},table=>[index('idx_users_locked').on(table.active,table.lockedUntil)]);
export const authSessions=sqliteTable('auth_sessions',{token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>staffUsers.id,{onDelete:'cascade'}),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull(),lastSeenAt:text('last_seen_at'),ipAddress:text('ip_address').notNull().default('')},table=>[index('idx_auth_user').on(table.userId,table.expiresAt)]);
export const assessmentCatalog=sqliteTable('assessment_catalog',{id:text('id').primaryKey(),name:text('name').notNull().unique(),minScore:integer('min_score').notNull().default(0),maxScore:integer('max_score').notNull(),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull(),version:text('version').notNull().default('1.0'),description:text('description').notNull().default('')});
export const programAssessments=sqliteTable('program_assessments',{programId:text('program_id').notNull().references(()=>programs.id,{onDelete:'cascade'}),assessmentId:text('assessment_id').notNull().references(()=>assessmentCatalog.id,{onDelete:'cascade'}),sortOrder:integer('sort_order').notNull().default(0)},table=>[primaryKey({columns:[table.programId,table.assessmentId]})]);
export const assessmentScores=sqliteTable('assessment_scores',{id:integer('id').primaryKey({autoIncrement:true}),applicationId:integer('application_id').notNull().references(()=>applications.id,{onDelete:'cascade'}),assessmentId:text('assessment_id').notNull().references(()=>assessmentCatalog.id,{onDelete:'cascade'}),preScore:real('pre_score'),postScore:real('post_score'),note:text('note').notNull().default(''),updatedAt:text('updated_at').notNull(),preDate:text('pre_date'),postDate:text('post_date'),notCompletedReason:text('not_completed_reason').notNull().default(''),assessor:text('assessor').notNull().default('')},table=>[unique().on(table.applicationId,table.assessmentId),index('idx_scores_application').on(table.applicationId)]);
export const satisfactionSurveys=sqliteTable('satisfaction_surveys',{id:integer('id').primaryKey({autoIncrement:true}),applicationId:integer('application_id').notNull().unique().references(()=>applications.id,{onDelete:'cascade'}),score:integer('score'),comment:text('comment').notNull().default(''),updatedAt:text('updated_at').notNull(),surveyVersion:text('survey_version').notNull().default('1.0'),anonymous:integer('anonymous').notNull().default(0)});
export const scheduleEvents=sqliteTable('schedule_events',{id:text('id').primaryKey(),eventType:text('event_type').notNull().default('상담'),color:text('color').notNull().default('green'),participantId:text('participant_id').notNull().references(()=>participants.id,{onDelete:'cascade'}),title:text('title').notNull(),eventDate:text('event_date').notNull(),allDay:integer('all_day').notNull().default(0),startTime:text('start_time').notNull().default(''),endTime:text('end_time').notNull().default(''),recurrence:text('recurrence').notNull().default('1회'),deliveryMode:text('delivery_mode').notNull().default('대면'),createdAt:text('created_at').notNull()},table=>[index('idx_schedule_events_date').on(table.eventDate,table.startTime),index('idx_schedule_events_participant').on(table.participantId)]);
